//! File-based settings store (issue #530): a `settings.toml` the app reads and
//! writes, layered with `settings.d/*.toml` drop-ins and `KOPUZ_CONFIG_*`
//! environment overrides so a Nix/hjem-managed (immutable) config works
//! without the app ever writing to it.
//!
//! TOML is the on-disk format because this file is meant to be hand-written and
//! generated by Nix (`pkgs.formats.toml`); the values themselves still travel as
//! `serde_json::Value`, which is what `AppConfig` round-trips through everywhere
//! else.
//!
//! Layering, lowest to highest precedence:
//! 1. whatever base the caller already has (the DB state blob),
//! 2. the settings file,
//! 3. drop-ins (`<stem>.d/*.toml`, lexicographic order),
//! 4. `KOPUZ_CONFIG_<FIELD>` environment variables.
//!
//! Keys pinned by a layer the settings UI cannot usefully edit — a managed
//! (Nix-store / read-only) file, any drop-in, any env var — are reported in
//! [`FileLayers::locked_keys`] so the UI can gray them out.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde_json::Value as JsonValue;
use toml::Value as TomlValue;

/// Env prefix for ad-hoc per-key overrides: `KOPUZ_CONFIG_THEME=nord`,
/// nested fields with `__` (`KOPUZ_CONFIG_EQUALIZER__ENABLED=true`).
pub const ENV_PREFIX: &str = "KOPUZ_CONFIG_";

/// `KOPUZ_CONFIG_PATH` relocates the settings file itself (it is not a field
/// override, so the env layer skips it).
pub const ENV_PATH_OVERRIDE: &str = "KOPUZ_CONFIG_PATH";

const NIX_STORE_PREFIX: &str = "/nix/store";

/// Runtime state, not settings: churns constantly or is per-install identity.
/// Never written to the settings file — it stays in the DB blob, so it keeps
/// persisting even when the settings file is immutable. (`server`/`servers`/
/// `listen_counts` additionally live in their own DB tables and are stripped
/// from every persisted form.)
const STATE_KEYS: &[&str] = &[
    "server",
    "servers",
    "listen_counts",
    "device_id",
    "offline_tracks",
    "ytdlp_history",
    "source_explicitly_set",
    "fullscreen_tabs_collapsed",
];

/// The settings file for an app whose database lives in `db_dir`:
/// `KOPUZ_CONFIG_PATH` override, else `<db_dir>/settings.toml` (release) or
/// `settings-debug.toml` (debug builds, mirroring the `kopuz-debug.db` split
/// so `dx serve` never touches real settings).
pub fn settings_path_for(db_dir: &Path) -> PathBuf {
    if let Ok(p) = std::env::var(ENV_PATH_OVERRIDE) {
        return PathBuf::from(p);
    }
    let name = if cfg!(debug_assertions) {
        "settings-debug.toml"
    } else {
        "settings.toml"
    };
    db_dir.join(name)
}

/// The drop-in directory belonging to a settings file: `settings.toml` →
/// `settings.d/` next to it (`settings-debug.toml` → `settings-debug.d/`).
pub fn dropin_dir_for(settings_path: &Path) -> PathBuf {
    let stem = settings_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("settings");
    settings_path.with_file_name(format!("{stem}.d"))
}

/// The read-side snapshot of every file/env layer, plus what the UI needs to
/// know about mutability.
#[derive(Debug, Clone, Default)]
pub struct FileLayers {
    /// The main settings file this snapshot was read from.
    pub path: PathBuf,
    /// Whether the main file existed at read time.
    pub file_exists: bool,
    /// The main file must not be written: it resolves into the Nix store or is
    /// read-only on disk.
    pub managed: bool,
    /// Top-level `AppConfig` keys pinned by an unwritable layer.
    pub locked_keys: BTreeSet<String>,
    /// Merged overrides (file → drop-ins → env) as a JSON object.
    overrides: JsonValue,
}

impl FileLayers {
    /// Read the file, its drop-ins, and the process environment.
    pub fn read(settings_path: &Path) -> Self {
        Self::read_inner(settings_path, NIX_STORE_PREFIX, std::env::vars())
    }

    fn read_inner(
        settings_path: &Path,
        store_prefix: &str,
        env: impl Iterator<Item = (String, String)>,
    ) -> Self {
        let mut overrides = JsonValue::Object(Default::default());
        let mut locked_keys = BTreeSet::new();

        let managed = is_managed(settings_path, store_prefix);
        let file_exists;
        if let Some(map) = read_toml_table(settings_path) {
            file_exists = true;
            if managed {
                locked_keys.extend(map.keys().cloned());
            }
            merge_into(&mut overrides, JsonValue::Object(map));
        } else {
            file_exists = settings_path.exists();
        }

        // Drop-ins always lock their keys: they out-rank the main file, so a
        // UI edit saved there could never take effect.
        let dropin_dir = dropin_dir_for(settings_path);
        for path in sorted_toml_files(&dropin_dir) {
            if let Some(map) = read_toml_table(&path) {
                locked_keys.extend(map.keys().cloned());
                merge_into(&mut overrides, JsonValue::Object(map));
            }
        }

        let env_layer = env_overrides(env);
        if let Some(obj) = env_layer.as_object() {
            locked_keys.extend(obj.keys().cloned());
        }
        merge_into(&mut overrides, env_layer);

        Self {
            path: settings_path.to_path_buf(),
            file_exists,
            managed,
            locked_keys,
            overrides,
        }
    }

    /// Whether any layer contributes anything at all.
    pub fn has_overrides(&self) -> bool {
        self.overrides.as_object().is_some_and(|o| !o.is_empty())
    }

    /// Whether the settings UI should treat a top-level config field as
    /// read-only.
    pub fn is_locked(&self, key: &str) -> bool {
        self.locked_keys.contains(key)
    }

    /// Deep-merge the layered overrides over `base` (a config JSON object).
    pub fn apply(&self, base: &mut JsonValue) {
        if self.has_overrides() {
            merge_into(base, self.overrides.clone());
        }
    }
}

/// Write the settings file from a full config JSON object (state keys are
/// stripped first), atomically via a sibling temp file. Returns `false`
/// without touching anything when the file is managed — an immutable config
/// is never written (issue #530).
pub fn save_settings_file(settings_path: &Path, cfg_json: &JsonValue) -> std::io::Result<bool> {
    if is_managed(settings_path, NIX_STORE_PREFIX) {
        tracing::debug!(path = %settings_path.display(), "settings file is managed; skipping write");
        return Ok(false);
    }

    let mut cfg = cfg_json.clone();
    let Some(obj) = cfg.as_object_mut() else {
        return Err(std::io::Error::other(
            "config did not serialize to an object",
        ));
    };
    for key in STATE_KEYS {
        obj.remove(*key);
    }
    let table = match json_to_toml(&cfg) {
        Some(TomlValue::Table(table)) => table,
        _ => {
            return Err(std::io::Error::other(
                "config did not serialize to a TOML table",
            ));
        }
    };
    let text = toml::to_string_pretty(&table).map_err(std::io::Error::other)?;

    // Follow a writable symlink to its target instead of replacing the link
    // with a regular file. (An hjem-managed link points into the store and
    // never gets here — this is for someone linking the file themselves.)
    let target = std::fs::canonicalize(settings_path).unwrap_or_else(|_| settings_path.to_owned());
    if let Some(parent) = target.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = target.with_extension("toml.tmp");
    std::fs::write(&tmp, text)?;
    std::fs::rename(&tmp, &target)?;
    Ok(true)
}

/// A file is "managed" when the app must not write it: it is (or resolves
/// through symlinks into) the Nix store, or it exists read-only.
fn is_managed(path: &Path, store_prefix: &str) -> bool {
    if let Ok(target) = std::fs::canonicalize(path)
        && target.starts_with(store_prefix)
    {
        return true;
    }
    match std::fs::metadata(path) {
        Ok(meta) => meta.permissions().readonly(),
        Err(_) => false,
    }
}

fn read_toml_table(path: &Path) -> Option<serde_json::Map<String, JsonValue>> {
    let text = std::fs::read_to_string(path).ok()?;
    match text.parse::<toml::Table>() {
        Ok(table) => match toml_to_json(TomlValue::Table(table)) {
            JsonValue::Object(map) => Some(map),
            _ => None,
        },
        Err(e) => {
            tracing::warn!(path = %path.display(), "ignoring unparsable config layer: {e}");
            None
        }
    }
}

fn sorted_toml_files(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "toml") && p.is_file())
        .collect();
    files.sort();
    files
}

/// Build the env layer: every `KOPUZ_CONFIG_<FIELD>` (except the path
/// override) becomes a lowercased field, `__` separating nested objects. The
/// value is parsed as a TOML value (`true`, `3`, `["a"]`, …), else taken as a
/// plain string.
fn env_overrides(env: impl Iterator<Item = (String, String)>) -> JsonValue {
    let mut layer = JsonValue::Object(Default::default());
    let mut vars: Vec<(String, String)> = env
        .filter(|(k, _)| k.starts_with(ENV_PREFIX) && k != ENV_PATH_OVERRIDE)
        .collect();
    vars.sort();
    for (key, raw) in vars {
        let path: Vec<String> = key[ENV_PREFIX.len()..]
            .split("__")
            .map(|s| s.to_lowercase())
            .filter(|s| !s.is_empty())
            .collect();
        if path.is_empty() {
            continue;
        }
        let value = parse_env_value(&raw);
        let mut nested = value;
        for part in path.iter().rev() {
            let mut obj = serde_json::Map::new();
            obj.insert(part.clone(), nested);
            nested = JsonValue::Object(obj);
        }
        merge_into(&mut layer, nested);
    }
    layer
}

/// Parse one env value as the right-hand side of a TOML assignment, so
/// `5`/`true`/`["a"]`/`"quoted"` keep their types and anything else (`nord`)
/// stays a bare string.
fn parse_env_value(raw: &str) -> JsonValue {
    format!("v = {raw}")
        .parse::<toml::Table>()
        .ok()
        .and_then(|mut t| t.remove("v"))
        .map(toml_to_json)
        .unwrap_or_else(|| JsonValue::String(raw.to_string()))
}

fn toml_to_json(value: TomlValue) -> JsonValue {
    match value {
        TomlValue::String(s) => JsonValue::String(s),
        TomlValue::Integer(i) => JsonValue::Number(i.into()),
        TomlValue::Float(f) => serde_json::Number::from_f64(f)
            .map(JsonValue::Number)
            .unwrap_or(JsonValue::Null),
        TomlValue::Boolean(b) => JsonValue::Bool(b),
        // No config field is a date; keep the text so it at least deserializes
        // into a string field instead of vanishing.
        TomlValue::Datetime(dt) => JsonValue::String(dt.to_string()),
        TomlValue::Array(items) => JsonValue::Array(items.into_iter().map(toml_to_json).collect()),
        TomlValue::Table(table) => JsonValue::Object(
            table
                .into_iter()
                .map(|(k, v)| (k, toml_to_json(v)))
                .collect(),
        ),
    }
}

/// TOML has no null: `None` fields are dropped, which is exactly right for
/// `AppConfig` (every field is `#[serde(default)]`, so an absent key restores
/// the default).
fn json_to_toml(value: &JsonValue) -> Option<TomlValue> {
    Some(match value {
        JsonValue::Null => return None,
        JsonValue::Bool(b) => TomlValue::Boolean(*b),
        JsonValue::Number(n) => match (n.as_i64(), n.as_f64()) {
            (Some(i), _) => TomlValue::Integer(i),
            (None, Some(f)) if f.is_finite() => TomlValue::Float(shorten_f32(f)),
            _ => return None,
        },
        JsonValue::String(s) => TomlValue::String(s.clone()),
        JsonValue::Array(items) => {
            TomlValue::Array(items.iter().filter_map(json_to_toml).collect())
        }
        JsonValue::Object(map) => TomlValue::Table(
            map.iter()
                .filter_map(|(k, v)| Some((k.clone(), json_to_toml(v)?)))
                .collect(),
        ),
    })
}

/// `serde_json` widens the config's `f32` fields to `f64`, so `volume = 0.05`
/// would land in the file as `0.05000000074505806`. A value that survives a
/// round trip through `f32` came from one, so write the short form a human
/// would have typed; anything genuinely `f64` keeps full precision.
fn shorten_f32(f: f64) -> f64 {
    let narrow = f as f32;
    if f64::from(narrow) != f {
        return f;
    }
    format!("{narrow}").parse().unwrap_or(f)
}

/// Deep merge: objects merge key-wise, everything else replaces.
fn merge_into(base: &mut JsonValue, layer: JsonValue) {
    match (base, layer) {
        (JsonValue::Object(base_map), JsonValue::Object(layer_map)) => {
            for (key, value) in layer_map {
                match base_map.get_mut(&key) {
                    Some(slot) if slot.is_object() && value.is_object() => {
                        merge_into(slot, value);
                    }
                    _ => {
                        base_map.insert(key, value);
                    }
                }
            }
        }
        (base, layer) => *base = layer,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::AppConfig;

    fn empty_env() -> impl Iterator<Item = (String, String)> {
        std::iter::empty()
    }

    #[test]
    fn default_config_round_trips_through_the_settings_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let cfg_json = serde_json::to_value(AppConfig::default()).unwrap();

        assert!(save_settings_file(&path, &cfg_json).unwrap());

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        let restored: AppConfig = serde_json::from_value(base).unwrap();

        let defaults = AppConfig::default();
        assert_eq!(restored.theme, defaults.theme);
        assert_eq!(restored.music_directory, defaults.music_directory);
        assert_eq!(restored.volume, defaults.volume);
        assert_eq!(restored.home_sections, defaults.home_sections);
        assert_eq!(restored.equalizer, defaults.equalizer);
        assert_eq!(restored.radio_registries, defaults.radio_registries);
        assert_eq!(restored.sidebar_order, defaults.sidebar_order);
        assert_eq!(restored.ytdlp_options, defaults.ytdlp_options);
    }

    #[test]
    fn f32_fields_are_written_short_and_reload_identically() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let cfg = AppConfig {
            volume: 0.35,
            volume_scroll_step: 0.05,
            ..Default::default()
        };

        save_settings_file(&path, &serde_json::to_value(&cfg).unwrap()).unwrap();

        let text = std::fs::read_to_string(&path).unwrap();
        assert!(
            text.contains("volume_scroll_step = 0.05\n"),
            "f32 widening leaked into the file:\n{text}"
        );

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        let restored: AppConfig = serde_json::from_value(base).unwrap();
        assert_eq!(restored.volume, cfg.volume);
        assert_eq!(restored.volume_scroll_step, cfg.volume_scroll_step);
    }

    #[test]
    fn state_keys_never_reach_the_settings_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        let mut cfg = AppConfig::default();
        cfg.offline_tracks
            .insert("track".into(), "/tmp/x.mp3".into());
        let cfg_json = serde_json::to_value(&cfg).unwrap();

        save_settings_file(&path, &cfg_json).unwrap();

        let written: toml::Table = std::fs::read_to_string(&path).unwrap().parse().unwrap();
        for key in STATE_KEYS {
            assert!(
                !written.contains_key(*key),
                "state key {key} leaked into the file"
            );
        }
    }

    #[test]
    fn dropins_and_env_out_rank_the_file_and_lock_their_keys() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "theme = \"nord\"\nlanguage = \"de\"\n").unwrap();
        let dropin_dir = dropin_dir_for(&path);
        std::fs::create_dir_all(&dropin_dir).unwrap();
        std::fs::write(dropin_dir.join("10-theme.toml"), "theme = \"dracula\"\n").unwrap();
        let env = vec![("KOPUZ_CONFIG_THEME".to_string(), "gruvbox".to_string())];

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, env.into_iter());

        let mut base = serde_json::json!({ "theme": "default", "volume": 0.5 });
        layers.apply(&mut base);
        assert_eq!(base["theme"], "gruvbox");
        assert_eq!(base["language"], "de");
        assert_eq!(base["volume"], 0.5);
        // A writable main file doesn't lock; drop-ins and env do.
        assert!(layers.is_locked("theme"));
        assert!(!layers.is_locked("language"));
        assert!(!layers.managed);
    }

    #[test]
    fn nested_toml_tables_merge_key_wise() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(
            &path,
            "[equalizer]\nenabled = true\npreamp_db = -3.0\npreset = \"Custom\"\n",
        )
        .unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        let mut base = serde_json::json!({ "equalizer": { "enabled": false, "bands": [1.0] } });
        layers.apply(&mut base);

        assert_eq!(base["equalizer"]["enabled"], true);
        assert_eq!(base["equalizer"]["preamp_db"], -3.0);
        // Untouched sub-keys survive the merge.
        assert_eq!(base["equalizer"]["bands"], serde_json::json!([1.0]));
    }

    #[test]
    fn env_values_parse_as_toml_with_string_fallback() {
        let env = vec![
            (
                "KOPUZ_CONFIG_CROSSFADE_SECONDS".to_string(),
                "5".to_string(),
            ),
            ("KOPUZ_CONFIG_THEME".to_string(), "nord".to_string()),
            (
                "KOPUZ_CONFIG_EQUALIZER__ENABLED".to_string(),
                "true".to_string(),
            ),
            (
                "KOPUZ_CONFIG_MUSIC_DIRECTORY".to_string(),
                r#"["/music", "/archive"]"#.to_string(),
            ),
            ("KOPUZ_CONFIG_PATH".to_string(), "/tmp/x.toml".to_string()),
        ];
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, env.into_iter());

        let mut base = serde_json::json!({});
        layers.apply(&mut base);
        assert_eq!(base["crossfade_seconds"], 5);
        assert_eq!(base["theme"], "nord");
        assert_eq!(base["equalizer"]["enabled"], true);
        assert_eq!(base["music_directory"][1], "/archive");
        // The path override is not a field.
        assert!(base.get("path").is_none());
        assert!(layers.is_locked("equalizer"));
    }

    #[test]
    fn read_only_file_is_managed_and_locks_its_keys_and_save_skips_it() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "theme = \"nord\"\n").unwrap();
        let mut perms = std::fs::metadata(&path).unwrap().permissions();
        perms.set_readonly(true);
        std::fs::set_permissions(&path, perms).unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());
        assert!(layers.managed);
        assert!(layers.is_locked("theme"));

        let cfg_json = serde_json::to_value(AppConfig::default()).unwrap();
        assert!(!save_settings_file(&path, &cfg_json).unwrap());
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "theme = \"nord\"\n"
        );
    }

    #[cfg(unix)]
    #[test]
    fn symlink_into_store_prefix_is_managed() {
        let dir = tempfile::tempdir().unwrap();
        let store = dir.path().join("nix-store");
        std::fs::create_dir_all(&store).unwrap();
        let target = store.join("abc-kopuz-settings.toml");
        std::fs::write(&target, "theme = \"nord\"\n").unwrap();
        let link = dir.path().join("settings.toml");
        std::os::unix::fs::symlink(&target, &link).unwrap();

        let layers = FileLayers::read_inner(&link, store.to_str().unwrap(), empty_env());

        assert!(layers.managed);
        assert!(layers.is_locked("theme"));
    }

    /// A hand-made link to a writable file: the write lands on the target and
    /// the link survives.
    #[cfg(unix)]
    #[test]
    fn writable_symlink_is_written_through_not_replaced() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("dotfiles-settings.toml");
        std::fs::write(&target, "theme = \"nord\"\n").unwrap();
        let link = dir.path().join("settings.toml");
        std::os::unix::fs::symlink(&target, &link).unwrap();

        let cfg_json = serde_json::to_value(AppConfig::default()).unwrap();
        assert!(save_settings_file(&link, &cfg_json).unwrap());

        assert!(std::fs::symlink_metadata(&link).unwrap().is_symlink());
        let written: toml::Table = std::fs::read_to_string(&target).unwrap().parse().unwrap();
        assert_eq!(written["theme"].as_str(), Some("default"));
    }

    #[test]
    fn missing_file_has_no_overrides_and_is_not_managed() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());

        assert!(!layers.has_overrides());
        assert!(!layers.managed);
        assert!(!layers.file_exists);
        assert!(layers.locked_keys.is_empty());
    }

    #[test]
    fn unparsable_file_is_ignored_rather_than_fatal() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.toml");
        std::fs::write(&path, "this is not = = toml\n").unwrap();

        let layers = FileLayers::read_inner(&path, NIX_STORE_PREFIX, empty_env());

        assert!(!layers.has_overrides());
        assert!(layers.file_exists);
    }
}
