[package]
name = "kopuz-hooks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true

[lib]
name = "hooks"

[lints]
workspace = true

[dependencies]
futures-util = { workspace = true }
tracing = { workspace = true }
dioxus = { workspace = true }
api = { workspace = true }
reader = { workspace = true }
utils = { workspace = true }
config = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
server = { workspace = true }
tokio = { workspace = true, features = ["fs", "sync", "macros"] }

[target.'cfg(target_os = "android")'.dependencies]
player = { workspace = true }
