[package]
name = "kopuz-kopuzd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true

[lib]
name = "kopuzd"

[[bin]]
name = "kopuzd"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
api = { workspace = true }
daemon = { workspace = true }
proto = { workspace = true }
config = { workspace = true }
db = { workspace = true }
reader = { workspace = true }
utils = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "signal"] }
tokio-stream = { workspace = true, features = ["net"] }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
directories = { workspace = true }
futures-util = { workspace = true }
libc = { workspace = true }
player = { workspace = true }

[dev-dependencies]
client = { workspace = true }
tempfile = { workspace = true }
async-trait = { workspace = true }
radio = { workspace = true }
